const condition = {
  NEGATIVE: "NEGATIVE",
  PRIMARY_HYPOTHYROID: "PRIMARY HYPORHYROID",
  SECONDARY_HYPOTHYROID: "SECONDARY HYPOTHYROID",
  COMPENSATED_HYPOTHYROID: "COMPENSATED HYPOTHYROID",
  HYPERTHYROID: "HYPERTHYROID",
  HYPOTHYROID: "HYPOTHYROID",
};

module.exports = condition;
